name: 🔖 Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  release:
    name: 🔖 Release (${{ github.ref_name }})
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: 🚚 Checkout (${{ github.ref_name }})
        uses: actions/checkout@v5

      - name: 📥 Cache library
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('./package-lock.json') }}

      - name: 🔖 Run semantic release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ github.token }}
